name: apiverve_bluetoothlookup
description: Bluetooth Company Lookup allows you to identify Bluetooth device manufacturers by their Bluetooth SIG assigned company identifier. This helps identify the manufacturer of Bluetooth devices, beacons, and accessories.
version: 1.1.13
homepage: https://apiverve.com/marketplace/bluetoothlookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/bluetoothlookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
