// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.BluetoothCompanyLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("companyId")]
        public long CompanyId { get; set; }

        [JsonProperty("companyIdHex")]
        public string CompanyIdHex { get; set; }

        [JsonProperty("found")]
        public bool Found { get; set; }

        [JsonProperty("company")]
        public string Company { get; set; }
    }
}
